language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "stable"

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/stats-go -covermode=count
  - bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile
